---
title: "Chapter 4"
author: "Michael Fryer"
date: "`r Sys.Date()`"
output:
  pdf_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

# Load Howell Data

```{r}
data("Howell1")
d <- Howell1
```
```{r, eval=FALSE, echo=FALSE}
precis(d)
```


## Filter data to only adults (18 and over)

```{r}
d <- d[d$age >= 18,]
```

# Model Creation

We will use prior simulation to create a model for this dataset.

## Define our first model using R's formula syntax (p. 88)

```{r}
set.seed(42)
m4.1 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu ~ dnorm(178, 20),
    sigma ~ dunif(0, 50)
  ),
  data=d
)
```
```{r, eval=FALSE, echo=FALSE}
precis(m4.1)
```

# Linear prediction (p. 97)

Again create a model for the data.

```{r}
set.seed(42)
N <- 100

xbar <- mean(d$weight)
m4.3 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * (weight - xbar),
    a ~ dnorm(178, 20),
    b ~ dlnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  data=d
)
```
```{r, eval=FALSE, echo=FALSE}
precis(m4.3)
```
Using the created model, we will simulate heights to find out our uncertainty. Then plot the results.
```{r}
# Adding mu uncertainty
weight.seq <- seq(from=25, to=70, by=1)
mu <- link(m4.3, data=data.frame(weight=weight.seq))
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob=0.89)
# Adding a prediction interval (prediction uncertainty due to std uncertainty)
sim.height <- sim(m4.3, data=list(weight=weight.seq))
height.PI <- apply(sim.height, 2, PI, prob=0.89)

# Plot raw data
plot(height ~ weight, data=d, col=col.alpha(rangi2, 0.7))
# Plot MAP line
lines(weight.seq, mu.mean)
# Plot HPDI region for line
shade(mu.PI, weight.seq)
# Plot PI region for simulated heights
shade(height.PI, weight.seq)
```


